name       : libid3tag
version    : 0.16.2
release    : 6
source     :
    - https://github.com/tenacityteam/libid3tag/archive/refs/tags/0.16.2.tar.gz : 96198b7c8803bcda44e299615e1929a85bd5a5da02e67ebc442735bc50018190
homepage   : https://github.com/tenacityteam/libid3tag
license    : GPL-2.0-later
component  : multimedia.library
summary    : Fork of the libid3tag library for reading ID3 metadata tags from MP3 files
description: |
    libid3tag is a library for reading and (eventually) writing ID3 tags, both ID3v1 and the various versions of ID3v2.
builddeps  :
    - gperf
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
