name       : libid3tag
version    : 0.15.1b
release    : 1
source     :
    - ftp://ftp.mars.org/pub/mpeg/libid3tag-0.15.1b.tar.gz : 63da4f6e7997278f8a3fef4c6a372d342f705051d1eeb6a46a86b03610e26151
license    : GPL-2.0
summary    : library for id3 tagging
description: |
    library for id3 tagging
builddeps  :
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
